name: Release

on:
  push:
    tags:
      - v*.*.*

jobs:
  release:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build executable for release
        run: swift build -c release --arch arm64 --arch x86_64 --product chatty
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: .build/apple/Products/Release/chatty
          token: ${{ secrets.GITHUB_TOKEN }}
